### ISSUE TITLE
ご連絡ください。

### ISSUE THREAD

**Issue by maemae1026** [masaki-kambe/groupBlue#1]
みんなで何を作成するかから相談して決めるのでしょうか。

**Comment by masaki-kambe** [comment]
・グループごとに付いてるチーム名の色をテーマカラーとする。
・各メンバーごとに別ぺージを作っていくとコンフリクトが起きないので、共同作業する領域を持つようにする分担する。
・何かしらのサイトのテーマや、作業する役割分担を決めておく。

ブートストラップ苦手すぎるんですけどとりあえずどのテンプレ使うか決めますか？

**Comment by maemae1026** [comment]
テンプレ決めましょう。
時間あまりないので

**Comment by masaki-kambe** [comment]
https://getbootstrap.com/docs/5.3/examples/product/
こんなのどうでしょうか

**Comment by k10k12** [comment]
それにしましょう。

**Comment by maemae1026** [comment]
ありがとうございます。
それにしましょう。

**Comment by masaki-kambe** [comment]
紹介する商品は何にしますか？
青いもの…

**Comment by masaki-kambe** [comment]
飲み物…とか？？

**Comment by maemae1026** [comment]
ドラえもん

**Comment by masaki-kambe** [comment]
まじで青いものですね笑

**Comment by masaki-kambe** [comment]
ドラえもんと道具紹介にしますか

**Comment by masaki-kambe** [comment]
とりあえず
・写真探す係
・HTMLの雛形修正
・CSSの修正
で割り振りますか

**Comment by k10k12** [comment]
承知です

**Comment by maemae1026** [comment]
いいのが思いつかないのでそうしましょう。

**Comment by masaki-kambe** [comment]
ブートストラップのCSS今の所できないので他の方にお願いしたいです…！！

**Comment by k10k12** [comment]
し、写真でいいでしょうか…

**Comment by maemae1026** [comment]
bootstrapのコードのコピペ方法からわからない状況です。
どちらかわかりますでしょうか

**Comment by masaki-kambe** [comment]
今自分も模索中です

**Comment by masaki-kambe** [comment]
分かりました？

**Comment by maemae1026** [comment]
デベロッパーツールでソースをコピーしようと思ったのですがうまくいかない状況です。
かんべさんがお送りいただいたURlですがどちらから遷移されましたでしょうか。

**Comment by k10k12** [comment]
何が何だかですorz

**Comment by masaki-kambe** [comment]
https://getbootstrap.com/docs/5.3/examples/

**Comment by masaki-kambe** [comment]
ここですね

**Comment by masaki-kambe** [comment]
ファイル見つけました！！！！！！！！

**Comment by masaki-kambe** [comment]
ここでは共有できないみたいですね…

**Comment by maemae1026** [comment]
了解です。プッシュお願いいただけますか。

**Comment by masaki-kambe** [comment]
今HTMLファイルとproduct.cssファイルGitHubにアップしました！

**Comment by masaki-kambe** [comment]
1回ブルできるか試してみます

**Comment by maemae1026** [comment]
imagesファイルと画像をプッシュしてみました。

**Comment by masaki-kambe** [comment]
なぜかアップしたファイルおかしいです…

**Comment by masaki-kambe** [comment]
GitHub上からアップロードすると問題あるんですかね

**Comment by maemae1026** [comment]
自分もわからないのですが、cssの参照がされてない？？

**Comment by k10k12** [comment]
そんな感じですよね

**Comment by maemae1026** [comment]
product.cssを適応してもダメだったので
いま空のstyle.cssの中身が必要そうです。

**Comment by masaki-kambe** [comment]
間違って閉じてしまいました。。

**Comment by masaki-kambe** [comment]
ローカル上では上手く表示されるんですけどプルした資源だと全然だめですね

**Comment by maemae1026** [comment]
bootstrap調べます。
どなたかわかったら教えてください。

**Comment by k10k12** [comment]
まさかの不在

**Comment by masaki-kambe** [comment]
送ったファイルローカル上だと上手く開けてますか？？

**Comment by masaki-kambe** [comment]
先に飯だけ買ってきます！

**Comment by k10k12** [comment]
送っていただいたものでも崩れてしまっています…

**Comment by maemae1026** [comment]
ご飯いきますね。
現在はローカルのファイル開いても崩れます。
リモートはcss適応なし。

リモートにてproduct.cssを適応すると
ローカルもリモートも同様の崩れになります。

**Comment by masaki-kambe** [comment]
資源上げ直したのでpullしてみてください！

**Comment by k10k12** [comment]
自分は崩れたままです…
前田さんはどうです？

**Comment by maemae1026** [comment]
pullができなくなり苦戦中です。。。
